dist: xenial
language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - &latest_ruby 2.6
  - jruby-head

matrix:
  include:
    - name: Profile Memory Usage
      rvm: *latest_ruby
      script: rake dev:profile_memory
    - name: HTML Validation
      before_install:
        - npm install vnu-jar
      script:
        - rake dev:generate_validation
        - java -jar node_modules/vnu-jar/build/dist/vnu.jar --root _validation --no-langdetect
  allow_failures:
    - rvm: jruby-head

addons:
  apt:
    packages:
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-latex-extra

before_install:
  - gem install rake
  - gem install minitest stringex
  - gem install rouge
  - gem install memory_profiler
  - wget https://github.com/htacg/tidy-html5/releases/download/5.4.0/tidy-5.4.0-64bit.deb
  - sudo apt purge libtidy-0.99-0
  - sudo dpkg -i tidy-5.4.0-64bit.deb

script: ruby -Ilib:test test/test_*
